name = "cubicsplines"
version = "0.1.0"
license = "license"
author = "Thomas"
maintainer = "thomas.biekoetter@desy.de"
copyright = "Copyright 2026, Thomas"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = true
test = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
[dependencies]
error-handling = { git = "https://github.com/SINTEF/fortran-error-handling.git", tag = "v0.2.0" }
[dev-dependencies]
csv-fortran = { git="https://github.com/jacobwilliams/csv-fortran.git" }
[[test]]
name = "trigo"
source-dir = "test"
main = "trigo.f90"
[[test]]
name = "smoothing"
source-dir = "test"
main = "smoothing.f90"

